apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
 name: cluster
spec:
 identityProviders:
 - name: keycloak
   mappingMethod: claim
   type: OpenID
   openID:
     clientID: ocp
     clientSecret:
       name: keycloak-client-secret
     ca:
       name: ca-config-map
     issuer: 'https://demo-helm-rh-keycloak-keycloak.apps-crc.testing/realms/openshift'
     claims:
        preferredUsername:
        - preferred_username
        name:
        - name
        email:
        - email